### ISSUE TITLE
Hanging tasks on Github Actions Ubuntu Runners (R CMD Check)

### ISSUE THREAD

**Issue by wlandau** [shikokuchuo/mirai#53]
As you know, I have been struggling with the final stages of https://github.com/ropensci/targets/pull/1044, which integrates `crew` into `targets`. `targets` encodes instructions in [special classed environments](https://github.com/ropensci/targets/blob/main/R/class_target.R) which govern the behavior of tasks and data. In `R CMD check` on GitHub Actions Ubuntu runners, when many of these objects are sent to and from `mirai()` tasks, the overall work stalls and times out. It only happens on GitHub Actions Ubuntu runners (probably Windows too, but it didn't seem worth checking), and it only happens inside `R CMD check`.

After about a week of difficult troubleshooting, I managed to reproduce the same kind of stalling using just `mirai` and `nanonext`. I have one example with 1000 tasks at https://github.com/wlandau/mirai/blob/reprex/tests/test.R, and I have another example at https://github.com/wlandau/mirai/blob/reprex2/tests/test.R which has 300 tasks and uses `callr` to launch the server process. In the first example, you can see time stamps starting at https://github.com/wlandau/mirai/actions/runs/4670004460/jobs/8269199542#step:9:105. The tasks get submitted within about a 20-second window, then something appears to freeze, and then the 5-minute timeout is reached. In the second example, the timestamps at https://github.com/wlandau/mirai/actions/runs/4670012640/jobs/8269219432#step:9:99 show activity within the first 8 seconds, and only 5 of the 300 tasks run within the full 5 minutes. (I know you have a preference against `callr`, but it was hard to find ways to get this problem to reproduce, and I think `mirai` servers can be expected to work if launched from `callr::r_bg()`.)

Sorry I have not been able to do more to isolate the problem. I still do not understand why it happens, and I was barely able to create examples that do not use `targets` or `crew`. I hope this much is helpful.

**Comment by shikokuchuo** [comment]
I can see the work you've put into this and fully commend the effort! Is your hypothesis that the instances are running out of memory on the Github runners? I can imagine they'd be quite resource constrained.

On my Ubuntu laptop, the 1,000 task reprex showed 3.55GB of memory usage at the end vs the 300 task example, which only took up about 400MB and ran quite snappily.

I can see the callr example on the Github runner only used 80MB memory in the end, but maybe that instance only had that much RAM remaining - so I'm not quite sure what to make of this.

**Comment by wlandau** [comment]
I just pushed https://github.com/wlandau/mirai/commit/30b6268e419c4facdb705a95b6d0700f34b80e02 to take more memory readings, and memory usage on the dispatcher and server do not look very different from beginning to end.

**Comment by shikokuchuo** [comment]
I was thinking just in terms of the client actually. As it's all on one machine. I assume caching to disk is set up so it doesn't OOM but will likely slow to a crawl - and that may be what we are experiencing.

It seems also it is _only on the Ubuntu runners_. I ran the same 1000 task reprex on Windows/Mac and it seems to succeed there. With Mac I have the printouts: https://github.com/shikokuchuo/mirai/actions/runs/4672218165/jobs/8274151885
Couldn't figure out on Windows, but looking at the test timing it is well within the timeout.

**Comment by shikokuchuo** [comment]
https://github.com/shikokuchuo/mirai/actions/runs/4672298324/jobs/8274326971 just calls `rnorm()` but succeeds on Mac and fails on Ubuntu. On the face of it suggests that it is a memory issue or some other peculiarity of the runners rather than something about the complexity of the input/output objects.

**Comment by shikokuchuo** [comment]
From my tests, it really seems that it is just the fact that the Ubuntu runners are memory constrained.

Everything works for small tasks of `rnorm(1e3)` size: https://github.com/shikokuchuo/mirai/actions/runs/4675768366
But not for larger objects e.g. `rnorm(3e5)`: https://github.com/shikokuchuo/mirai/actions/runs/4675934509

For the Mac machine the tests consistently run all the way through without problem.
The only command is `rnorm()` and the return value is just a vector of doubles so nothing complex going on.

Given the above, I don't believe this is a cause of concern.
Indeed you may wish to try your `targets` tests again, but ensuring the payloads are minimal.

**Comment by wlandau** [comment]
In `targets`, I just re-enabled `crew` tests on Mac OS. In the [previous workflow without `crew tests`](https://github.com/ropensci/targets/actions/runs/4671028435/jobs/8271505314), the check time was around 9 minutes. [With `crew` tests](https://github.com/ropensci/targets/actions/runs/4676969469/jobs/8283920744), check time was around 12 minutes. (It also appears to have trouble saving the package cache, but that is probably unrelated.)

**Comment by shikokuchuo** [comment]
> If it is just R CMD check + Ubuntu + GitHub Actions + 1 GB memory, this is not so limiting. But it makes me worry about how this may affect data-heavy workloads on normal machines.

Honestly I'm not worried until I see it outside of Github actions. Our main production machine runs Ubuntu on 'data-heavy' workloads using `mirai` literally 24/7.

The tests vary on Ubuntu - sometimes it finishes only 1 task, sometimes up to 10 - so we can rule out a deterministic reason. It strongly suggests an external cause, which given we can't replicate the behaviour anywhere else, we can't diagnose.

> In `targets`, I just re-enabled `crew` tests on Mac OS. In the [previous workflow without `crew tests`](https://github.com/ropensci/targets/actions/runs/4671028435/jobs/8271505314), the check time was around 9 minutes. [With `crew` tests](https://github.com/ropensci/targets/actions/runs/4676969469/jobs/8283920744), check time was around 12 minutes. (It also appears to have trouble saving the package cache, but that is probably unrelated.)

Yes, that's a good idea to enable on Mac.

**Comment by shikokuchuo** [comment]
However, all your hard work does have a good result:

Seeing the memory usage on your 1,000 test case caused me to re-visit memory handling.

In fact I had attempted to optimise this a couple of weeks ago, but this led to the failures in the throughput tests (with the memory corruption errors). I am now taking a slightly different approach by simply removing the reference to the 'aio' external pointer when the results have been retrieved (and cached). This will allow the garbage collector to reclaim the resources in its own time.

If you have additional testing scripts, please can you re-run on nanonext 0.8.1.9016 and mirai 0.8.2.9023. I would like to make sure I haven't broken anything inadvertently.

I will also need to run this on a staging machine to monitor, but if successful should be in a position to release `nanonext` to CRAN at some point tomorrow. The recent builds have been really solid.

**Comment by wlandau** [comment]
Thank you so much! Your updates to `nanonext` and `mirai` appear to have eliminated problems in the `targets` tests, which was what I was mainly worried about. The load tests in `crew` still appear to hang and time out, but because of the high loads in those tests, I am willing to believe the problem is indeed due to constrained memory on Ubuntu runners.

I am really excited for the next CRAN releases of `nanonext` and `mirai`. After that, I can release `crew` and then `targets`, broadcast our progress, and invite others to write their own `crew` launchers.

**Comment by shikokuchuo** [comment]
Thanks that's really good news!

**Comment by shikokuchuo** [comment]
I wasn't actually trying to fix the test issues... just a note before I forget - the 'aios' now pretty much clean up after themselves as soon as `unresolved()` returns successfully or after `call_mirai()` or after the `$data` is actually accessed. Note that it'd be a mistake to make a copy of an 'aio' before that point as you'd duplicate the reference to the external pointer. Just an FYI as I know you hang on to the 'aios'.

**Comment by wlandau** [comment]
Thanks, noted. When crew checks a task, it uses the more minimal .unresolved() from nanonext, then moves the resolved mirai object from the list of tasks to the list of results. After that, the user can call controller$pop() to download the data and release the aio. From what I know about R's copy-on-modify system, I believe this approach avoids copying the pointer. At any rate, the tests I need to pass are passing, thanks to you.

**Comment by shikokuchuo** [comment]
Yes, actually I was being too conservative - the `mirai` are environments so if you copy them just the reference to the environment is duplicated. The external pointer sits within the environment, and is the same no matter through which reference you access it. And the cleanup works regardless. Forget my previous comment!!

**Comment by wlandau** [comment]
FYI it appears I am still getting intermittent hanging tests on R CMD check. The good news is that it still works most of the time, so I have implemented timeouts and retries as a workaround. I think that's good enough for me for now. Maybe we could just keep an eye on it going forward?

**Comment by wlandau** [comment]
For example, the workflow at https://github.com/ropensci/targets/actions/runs/4684600263/jobs/8300914514 reached a timeout in a `crew` test, but the first retry succeeded.

**Comment by shikokuchuo** [comment]
> Maybe we could just keep an eye on it going forward?

Might be able to fix it these couple of days hopefully. I'm trying to pin down this elusive segfault on CRAN OpenBlas machine ( I mentioned before all these exotic setups tend to get me!!)

In the middle of simplifying and making more robust certain things in `nanonext`, which  will push back the release slightly.

However, I've also cut out the new features we're not using yet so that `mirai` only depends on the existing `nanonext` 0.8.1. So should be able to release around the same time.

**Comment by shikokuchuo** [comment]
OK! Do you want to re-run your tests with `nanonext` [fb8b05d](https://github.com/shikokuchuo/nanonext/commit/fb8b05d7175b26b1158494114902cb4759f976f5) v0.8.1.9020 and `mirai` [4e1862e](https://github.com/shikokuchuo/mirai/commit/4e1862efa4e9840dfdd51b0c59c2800c7fd97754) v0.8.2.9027.

I have taken to testing across (a good selection of) the rhub platforms and the segfault no longer appears (was quite consistently, although randomly reproducible for the last CRAN release). The changes have a good chance of also fixing your hanging tests.

**Comment by wlandau** [comment]
Thanks for working on this. I just pushed updates to `crew` and `targets` that use those versions of `mirai` and `nanonext`, and I look forward to trying more updates when you are ready.

**Comment by shikokuchuo** [comment]
I think nanonext v0.8.1.9020 or the latest v0.8.1.9022 should do the trick actually. `crew` always uses the dispatcher right? There are some edge cases without the dispatcher I need to make safe. But otherwise I think should be fine. Do let me know if anything seems to be off. Thanks!

**Comment by wlandau** [comment]
With  nanonext v0.8.1.9021 and mirai 0.89.2.9027, I did observe one hanging test which succeeded on the first retry: https://github.com/ropensci/targets/actions/runs/4690189013/jobs/8315468527#step:9:258. Another just like it ran on Mac OS: https://github.com/ropensci/targets/actions/runs/4690189013/jobs/8315467814#step:10:257. Currently trying again with `nanonext` 0.8.1.9022. Interestingly, I am seeing "read ECONNRESET" in the annotations at https://github.com/ropensci/targets/actions/runs/4690189013. Not sure if that is related.

**Comment by wlandau** [comment]
With nanonext v0.8.1.9021, it looks like all the targets checks succeeded on the first try. I am running the jobs again to confirm.

**Comment by wlandau** [comment]
Meant to say v0.8.1.9022 above.

**Comment by wlandau** [comment]
In later commits of `targets` using mirai 0.8.2.9027 and nanonext 0.8.1.9022, I unfortunately still notice sporadic hanging. Examples:

* https://github.com/ropensci/targets/actions/runs/4692986126/jobs/8319383756#step:10:278
* https://github.com/ropensci/targets/actions/runs/4693001773/jobs/8319416978#step:10:277

**Comment by shikokuchuo** [comment]
nanonext 0.8.1.9025 and mirai 0.8.2.9028 are the release candidates. If final testing doesn't throw any errors, nanonext on track for release tmrw.

If you notice any particular occasions it hangs e.g. when scaling up / down etc. I will have more to go on. I have covered the general bases - it is much more robust (and actually more performant it seems).

**Comment by wlandau** [comment]
Glad you're seeing performance gains, and I'm glad the packages are poised for CRAN. I'm afraid I do still see the same timeouts with nanonext 0.8.1.9025 and mirai 0.8.2.9028. The commits to https://github.com/ropensci/targets/tree/try-builds since https://github.com/ropensci/targets/commit/8b4cf6ecb6cf6f9002f776128f1036e6a128b05b show intermittent failures testing `crew`. I disabled the retries on that branch so they would be easier to see.

**Comment by shikokuchuo** [comment]
That seems like it will be helpful - at the moment I'm not seeing a pattern, unless you can spot something.

In any case I've added more safety to mirai 0.8.2.9030. I think this could be the one that solves it. In any case, I think I'll be able to further refine through changes to `mirai` alone, and `nanonext` is good to go. No segfaults at least so it solves the CRAN issue  - if you see any please let me know straight away. Thanks!

**Comment by wlandau** [comment]
I am still noticing sporadic hanging e.g. https://github.com/ropensci/targets/actions/runs/4698586073/jobs/8331053726#step:9:249. I do not see a pattern either, but it only happens in a niche setting, and maybe more clues will arise a couple releases later. Thank you for all the progress you have made despite incomplete information from me.

**Comment by wlandau** [comment]
I am sure you have seen this, but just in case you haven't, it looks like `mirai` 0.8.2.9030 is not compatible with `nanonext` 0.8.1.9026:

```r
> packageVersion("nanonext")
[1] ‘0.8.1.9026’
> packageVersion("mirai")
[1] ‘0.8.2.9030’
> library(mirai)
> library(nanonext)
> daemons(
+   n = 1L,
+   url = "ws://127.0.0.1:5000",
+   disaptcher = TRUE,
+   token = TRUE
+ )
[1] 1
> while (is.null(nrow(daemons()$daemons))) {
+   msleep(10)
+ }
> socket <- as.character(rownames(daemons()$daemons))
> launch_server(url = socket)
> task <- mirai(TRUE)
Error in request(context(..[[.compute]][["sock"]]), data = envir, send_mode = 1L,  : 
  unused argument (socket = length(..[[.compute]][["sockc"]]) || stat(..[[.compute]][["sock"]], "pipes"))
```

**Comment by shikokuchuo** [comment]
Yes thanks you beat me to it. Was having connection issues here at the CMS in Cambridge so found a place up top with mobile reception. mirai v0.8.1.3031 is the corresponding version, just uploaded. It's good you're still tracking this. Would be great to get a final test run based on those versions before I release nanonext.

Behaviour should be the same, although the implementation is *miles* better. But you never know, it might solve the hanging...

**Comment by wlandau** [comment]
Thanks! The intermittent hanging is still there, but I really appreciate the lengths you are going to refine `nanonext` and `mirai`.

**Comment by shikokuchuo** [comment]
nanonext has been submitted but is now in ‘waiting’ as I inadvertently broke ‘mirai’ by removing a function I didn’t want to maintain going forward and forgetting to check using the old version! I did check your existing version of crew.

**Comment by shikokuchuo** [comment]
The past few builds of `mirai` have been really quite solid, and I am prepared for a CRAN release. The latest dev version is 0.8.2.9036.

I have added a 'force' argument to `saisei()` so you can rotate listeners even when there is a connection. Just in case it is useful for hanged process (it releases the task and re-assigns it - it doesn't lose the task any more as we are not terminating sockets). The result is the same as terminating the server process directly - but this is probably easier locally than if it were actually remote.

I'll give you time to test things thoroughly on Monday. I hope you are comfortable with where things are. I think I have done as much as I can at this stage and I'm sure real life usage reports will help narrow down the cause of any hangs.

**Comment by wlandau** [comment]
Awesome! `mirai` 0.8.2.9037 and 0.8.2.9038 work just as well with `crew` and `targets` as before. Still intermittent hanging for those tests on `R CMD check` on Ubuntu runners, but the real tests that matter work really well. I am ready for a `mirai` release when you are.

> I have added a 'force' argument to saisei() so you can rotate listeners even when there is a connection. Just in case it is useful for hanged process (it releases the task and re-assigns it - it doesn't lose the task any more as we are not terminating sockets). The result is the same as terminating the server process directly - but this is probably easier locally than if it were actually remote.

Thanks for this. I added `saisei(force = TRUE)` to the `crew` code that terminates "lost" workers that time out trying to launch, just for a little extra robustness.

**Comment by shikokuchuo** [comment]
Fantastic! There is one last thing that came to me whilst I was working on the above - and this is to do with NNG's retry mechanism, which we have 'magically' relied on without seeking to control directly.

This could well be responsible for hangs or other odd behaviour. In mirai 0.8.2.9039 I have tuned this so it won't try and resend to another socket. It will still retry on the same socket i.e. if an instance times out, listener is rotated etc. The rather critical reason being that currently it could try to send a long-running task multiple times to different servers!

There are other ways to gain even more granular control, but if the above works on your real tests then that would be best. The `crew` tests pass, but you probably need to run for `targets` etc.

Thanks!

**Comment by wlandau** [comment]
Thanks for trying again. I saw hanging in 4 out of the last 16 targets GHA test runs, but hopefully that’s another clue.

**Comment by shikokuchuo** [comment]
Ok, sure we’ll have to leave that for another day then. But nothing else has broken? I just wanted to double check with you as it is a real change in behaviour - once a task gets sent to a socket it will now remain at that socket.On 16 Apr 2023, at 15:05, Will Landau ***@***.***> wrote:﻿
Thanks for trying again. I saw hanging in 4 out of the last 16 targets GHA test runs, but hopefully that’s another clue.

**Comment by wlandau** [comment]
> Ok, sure we’ll have to leave that for another day then. But nothing else has broken? I just wanted to double check with you as it is a real change in behaviour - once a task gets sent to a socket it will now remain at that socket.

I just reran the throughput tests of `crew` and `targets` locally with `mirai` 0.8.2.9039 (as well as one of the throughput tests of the upcoming `crew.cluster`, still not open-source yet). All the results look good.

> Btw. of the 4 test failures, 2 do not seem to be within `class_crew` - and then of the `class_crew` ones it is a different one each time.

There is also a `tar_make()` test that uses `crew`, and sometimes that is the only one which fails: https://github.com/ropensci/targets/blob/f5202dbe20f82922a630feede9714197bfb34e1c/tests/testthat/test-tar_make.R#L17-L47

**Comment by shikokuchuo** [comment]
Fantastic! All tests looking good on my side as well. Will leave it to run for a while on our workflow, and then release to CRAN later this evening.

**Comment by wlandau** [comment]
Sounds great!

By the way, I have been printing out more diagnostic info from the `crew` controller. Many times, the worker is assigned a task, but it does not complete: https://github.com/ropensci/targets/actions/runs/4715544592/jobs/8362602856#step:9:278. Other times (fewer cases), daemons()$daemons is not a matrix even though the dispatcher is supposed to be running: https://github.com/ropensci/targets/actions/runs/4715546457/jobs/8362605843#step:9:225

**Comment by wlandau** [comment]
More clearly printed examples of each are at https://github.com/ropensci/targets/actions/runs/4715910056/jobs/8363186686#step:9:242 and https://github.com/ropensci/targets/actions/runs/4715910056/jobs/8363186593#step:9:238, respectively. To be clear, I am fine to simmer on this one and return to it if an idea occurs to you or we get more information from real-world usage.

**Comment by wlandau** [comment]
Also: those output logs, "daemons: NULL" just means daemons()$daemons was not an integer matrix. Most likely it returned 0 and the crew router object did not accept it and instead recorded NULL internally.

**Comment by HenrikBengtsson** [comment]
FWIW, if those log outputs are useful for future troubleshooting, you may want to pursue the output in your comment above, before GitHub clear the logs.

**Comment by shikokuchuo** [comment]
Thanks! Unfortunately it still only tells us what we already know which is that sometimes processes can hang or appear to hang.

First - just on the results:

+ the non-matrix return value is not a bug as it is behaving as expected. All NNG messages either return what you expect or an error value which can be tested with `is_error_value()`. In this case it will be a 5 timed out error. I realise that this isn't documented explicitly in this case so I will fix this.
+ the unfinished task - that is helpful in that we are now fairly certain that the process has just not completed the task - has hung or is so slow it appears to be hung.

Now to summarise where we are, this occurs:
- only Github Actions Ubuntu and only up to ~25% of the time
- even on Github Actions works for Mac and Windows
- works on Ubuntu outside of GHA

Given the above, my only hypothesis at the moment is that due to the low amount of resources assigned to Ubuntu instances (which we saw on the early tests), that the kernel is simply held by other processes and not returned to us in a timely manner. `targets` tests are longer running and that is why it manifests there. Sometimes I am waiting for test results and I see the Github process hang up to 20mins or so on another step (outside of tests) so I believe this is entirely possible.

If you have other hypotheses (however unlikely) please let me know as otherwise we'll suffer from confirmation bias in looking to prove/disprove the above when it could be that we should be looking somewhere else entirely.

I suggest if you can reproduce on rhub we might look at it again, otherwise we can wait for real world issues. I have been using the below combination to debug the recent OpenBLAS issue (nothing to do with OpenBLAS - it just happened to trigger on that configuration):
```r
rhub::check_for_cran(platforms = c("linux-x86_64-rocker-gcc-san", "fedora-clang-devel", "debian-gcc-devel", "debian-clang-devel"))
```
I consider this issue closed unless reproducible on rhub.

**Comment by wlandau** [comment]
Amazing! I am so excited to update `crew` when the `mirai` builds complete on CRAN.

I will also try Rhub on the platforms you suggested for testing the `targets`/`crew` integration.

**Comment by shikokuchuo** [comment]
Changing tack, can you test if [70af31d](https://github.com/shikokuchuo/mirai/commit/70af31d4f4ac285912a2c53abb9cd6fffaf2fe76) might have solved this?

I was reimplementing the solution to #32 using synchronisation 7992b03 when I had a brainwave. It if solves the problem there, it could also solve the problem here.

**Comment by wlandau** [comment]
Once again, thanks for trying. I still do see a persistently unresolved `mirai` task in workflows like https://github.com/ropensci/targets/actions/runs/4752769291/jobs/8445327593#step:9:206.

**Comment by shikokuchuo** [comment]
I do believe this is now fixed via [f303182](https://github.com/shikokuchuo/mirai/commit/f3031821e02b4afec22e651b607a5c43825e42d8) (v0.8.3.9027).
The mirai-only reprex completes every time: https://github.com/shikokuchuo/mirai/actions/runs/4915843147

**Comment by wlandau** [comment]
Thanks so much for keeping this problem in mind. I have been thinking about it too, and over the past few days I have been trying to isolate it.

Unfortunately, tests on my end are still hanging and timing out using `mirai` 0.8.3.9027. https://github.com/ropensci/targets/actions/runs/4916196900/jobs/8779637216 is a large number of replications of the `targets` tests that are giving me trouble.

https://github.com/ropensci/targets/blob/mirai-with-targets-task/tests/test-mirai-with-targets-task.R is another reproducible that intermittently hangs (results: https://github.com/ropensci/targets/actions/runs/4916144545/jobs/8779524136). This one might be a more useful example because it calls `mirai` directly (although the task in `.expr` still uses `targets`). Here is the code:

```r
library(mirai)
library(R.utils)
library(targets)
for (rep in seq_len(100)) {
  print(rep)
  target <- tar_target(y, 1)
  daemons(n = 1L, url = "ws://127.0.0.1:0", token = TRUE)
  url <- NULL
  while (!length(url)) {
    url <- as.character(rownames(daemons()$daemons))
  }
  launch_server(url = url)
  task <- mirai(
    .expr = targets:::target_run(target, globalenv(), "_targets"),
    .args = list(target = target)
  )
  withTimeout(
    while (TRUE) {
      Sys.sleep(1)
      data <- task$data
      if (inherits(data, "tar_target")) {
        break
      }
    },
    timeout = 60
  )
  daemons(n = 0L)
  if (!inherits(data, "tar_target")) {
    stop("task still unresolved after a minute")
  }
  rm(target)
  gc()
}
```

I can occasionally reproduce the hanging using a GitHub Codespace based created from https://github.com/ropensci/targets/blob/mirai-with-targets-task. I don't know how to share the image with you directly, but the branch has the `Dockerfile` and the `.devcontainer/devcontainer.json`.

Alternatively, you might also be able to explore the hanging by inserting a [`tmate`](https://github.com/mxschmitt/action-tmate) step in https://github.com/ropensci/targets/blob/mirai-with-targets-task/.github/workflows/check.yaml. Although there it's a bit less convenient because there does not seem to be a way to open more than one terminal process.

**Comment by shikokuchuo** [comment]
Ok - these tests are failing every time. Are you able to run the original tests that corresponded to the mirai-only reprex you produced? Because those are now working consistently for me. The ones where we were getting 3 or 4 failures in 12 or 15 tests. I want to be clear what exactly what we're fixing - as I do believe the issue we had before has been fixed.

**Comment by wlandau** [comment]
> Ok - these tests are failing every time.

The original tests were failing intermittently, so I made the script loop over 100 reps.

> Are you able to run the original tests that corresponded to the mirai-only reprex you produced?

Those original tests are still failing intermittently on GitHub Actions. In https://github.com/ropensci/targets/tree/debug-targets, I picked one of those problematic tests and looped it 100 times: https://github.com/ropensci/targets/blob/bb11a35e6b35fcf460d78b769a54355c2e87d343/tests/testthat/test-class_crew.R#L3-L58 (results: https://github.com/ropensci/targets/actions/runs/4916196900).

 > Because those are now working consistently for me.

Are you running them locally? They run without error on my local machine too. (Sometimes my Ubuntu installation hangs, but rarely.)

**Comment by wlandau** [comment]
> Ok, I just wanted to make sure we're not chasing a moving target.

Yeah, I agree that's a good thing to check. Just to be sure, I created a fresh new branch with the tests closer to their original state: https://github.com/ropensci/targets/tree/debug-targets-original. Tests are running now: https://github.com/ropensci/targets/actions/runs/4916913580

> I'm referring to the results: https://github.com/shikokuchuo/mirai/actions/runs/4915843147
> using your test code here: https://github.com/shikokuchuo/mirai/blob/dev/tests/tests.R
> There are 2 sets of test runs that worked - that's why I thought the problem had been fixed.

That's definitely progress! Odd that the `targets` tests still have trouble even though the `mirai`-only ones work now.

**Comment by shikokuchuo** [comment]
> That's definitely progress! Odd that the targets tests still have trouble even though the mirai-only ones work now.

Thanks - I've run the tests 5x now - so 40 in total (35 on Ubuntu, 5 on Mac). So it does appear to address that particular situation.

The other tests will be useful in letting me know if I need to do more on this particular fix, or it's likely to be another issue altogether!

**Comment by wlandau** [comment]
Yeah, I think the current issue may be different from the one you fixed (which is news to me). Looks like many of the jobs at https://github.com/ropensci/targets/actions/runs/4916913580/jobs/8781292763 are timing out.

**Comment by shikokuchuo** [comment]
Fantastic - this is very helpful!

`mirai` [3dbe12c](https://github.com/shikokuchuo/mirai/commit/3dbe12c978290e953ecd5960be430056e8821231) v0.8.3.9028. This either solves these hanging issues or we know it is something else. Please have a re-run of all the tests.

FYI the issue I fixed was with the use of `cv_reset()` - as CVs are being modified asynchronously, we cannot be certain the order in which events occur. So to be extra safe, ensure it is not this causing any problems, I have eliminated this use entirely. All that this means is that 'instance' doesn't reset to zero when `saisei()` is called. This doesn't break `crew` tests - just to be noted in case you rely on this anywhere else  - it is definitely not worth the potential problems for this tiny bit of state!

**Comment by wlandau** [comment]
Sorry, but it appears https://github.com/shikokuchuo/mirai/commit/3dbe12c978290e953ecd5960be430056e8821231 broke the semi-automated test in https://github.com/wlandau/crew/blob/main/tests/throughput/test-transient.R. `crew` relies on the `instance` counter to check if a worker is "discovered": https://github.com/wlandau/crew/blob/29fbcd53991022ac6fa6b596cd5b7e5eb805b9d8/R/crew_controller.R#L567-L576. Reverting to f3031821e02b4afec22e651b607a5c43825e42d8 appears to fix that issue.

**Comment by shikokuchuo** [comment]
> Sorry, but it appears [3dbe12c](https://github.com/shikokuchuo/mirai/commit/3dbe12c978290e953ecd5960be430056e8821231) broke the semi-automated test in https://github.com/wlandau/crew/blob/main/tests/throughput/test-transient.R. `crew` relies on the `instance` counter to check if a worker is "discovered": https://github.com/wlandau/crew/blob/29fbcd53991022ac6fa6b596cd5b7e5eb805b9d8/R/crew_controller.R#L567-L576. Reverting to [f303182](https://github.com/shikokuchuo/mirai/commit/f3031821e02b4afec22e651b607a5c43825e42d8) appears to fix that issue.

Will it break the hanging tests though? If it solves the hanging, we can find a workaround for this or vice versa.

**Comment by wlandau** [comment]
Oh, right, I can check the hanging even though the transient worker tests are temporarily failing. I will do that.

Another thing we could try is run the Dockerfile at https://github.com/ropensci/targets/blob/mirai-with-targets-task/Dockerfile locally with limited resources (i.e. `--memory="4g"` and `--cpus="1"`).

**Comment by shikokuchuo** [comment]
Great - let's see what happens! I no longer think this is a resource issue btw. From what I've seen, and the seemingly stochastic nature of failures, I believe it is to do with the timing of asynchronous events that we reason to be in order, but actually occur out of order at times.

**Comment by wlandau** [comment]
Comparing test results [before](https://github.com/ropensci/targets/actions/runs/4916913580) and [after](https://github.com/ropensci/targets/actions/runs/4918425447/jobs/8784736318), there looks to be noticeably less hanging (from 7 failures down to 2 failures out of 20 test runs). So this looks to be the right area to focus on. Very exciting!

**Comment by shikokuchuo** [comment]
Right! Given that some of the successful tests take > 40s, I wonder if they might pass if the time limit was set a bit wider from the 60s?

**Comment by wlandau** [comment]
I will try that right now.

**Comment by wlandau** [comment]
That time limit was only ever meant to guard against the 6-hour case anyway.

**Comment by wlandau** [comment]
Hmm... looks as though there is still some hanging even with a 360-second timeout: https://github.com/ropensci/targets/actions/runs/4918659918/jobs/8785280957.

**Comment by shikokuchuo** [comment]
> Hmm... looks as though there is still some hanging even with a 360-second timeout: https://github.com/ropensci/targets/actions/runs/4918659918/jobs/8785280957. In real life, I would not expect a pipeline so short to take as long as 6 minutes.

Yes agree, it looks like something else is going on here. But I think it is still an improvement on before, so I think it does guard against some of the hangs.

**Comment by shikokuchuo** [comment]
Ok, you have your previous 'instance' behaviour back in [d56d042](https://github.com/shikokuchuo/mirai/commit/d56d0427be6b1ab8a67c898b0f809a77c9acffe4) v0.8.3.9029. This is just a counter (some arithmetic) and doesn't drive anything in `mirai` so I'm confident it doesn't break anything that has been fixed. The mirai-only tests are all working.

**Comment by wlandau** [comment]
Only 2 timeouts out of 20 runs this time: https://github.com/ropensci/targets/actions/runs/4919322001/jobs/8786791656

Given how much more actionable this issue is, do you think we should formally reopen it?

**Comment by shikokuchuo** [comment]
> 
> ```r
> library(mirai)
> library(R.utils)
> library(targets)
> for (rep in seq_len(100)) {
>   print(rep)
>   target <- tar_target(y, 1)
>   daemons(n = 1L, url = "ws://127.0.0.1:0", token = TRUE)
>   url <- NULL
>   while (!length(url)) {
>     url <- as.character(rownames(daemons()$daemons))
>   }
>   launch_server(url = url)
>   task <- mirai(
>     .expr = targets:::target_run(target, globalenv(), "_targets"),
>     .args = list(target = target)
>   )
>   withTimeout(
>     while (TRUE) {
>       Sys.sleep(1)
>       data <- task$data
>       if (inherits(data, "tar_target")) {
>         break
>       }
>     },
>     timeout = 60
>   )
>   daemons(n = 0L)
>   if (!inherits(data, "tar_target")) {
>     stop("task still unresolved after a minute")
>   }
>   rm(target)
>   gc()
> }
> ```
> 

Btw. the above test you suggested, I just tried it on Github here: https://github.com/shikokuchuo/mirai/actions/runs/4919282417 and all tests pass.

I changed it to a slightly more efficient version of the same test that uses a mirai with timeout and `call_mirai()` in place of the polling, and got one failure: https://github.com/shikokuchuo/mirai/actions/runs/4919433912

Again, this one seems it is 'almost fixed'.

**Comment by shikokuchuo** [comment]
> Only 2 timeouts out of 20 runs this time: https://github.com/ropensci/targets/actions/runs/4919322001/jobs/8786791656
> 
> Given how much more actionable this issue is, do you think we should formally reopen it?

That's good. I think I've taken it as far as I can along this line of thinking, and it has yielded a definite improvement. I am trying something else in v0.8.3.9030 - package testing on all platforms at the moment.

**Comment by shikokuchuo** [comment]
A clean slate here: https://github.com/shikokuchuo/mirai/actions/runs/4919787543... dare I say it? :)

**Comment by wlandau** [comment]
Awesome! I'm noticing a huge improvement on my end too, only one timeout at https://github.com/ropensci/targets/actions/runs/4920543195.

**Comment by shikokuchuo** [comment]
Using the simple test code here: https://github.com/shikokuchuo/mirai/blob/dev/tests/tests.R
I am getting a pass on all except one https://github.com/shikokuchuo/mirai/actions/runs/4925269509/jobs/8799289113 - which really hangs (does not time out as it's supposed to).

It's quite puzzling as I've walked though the code and nowhere should it hang (those places have timeouts implemented). 

The only thing that is 'wrong' with the test code is this spin cycle:
```r
while (!length(url)) {
    url <- as.character(rownames(daemons()$daemons))
  }
```
I am wondering if in crew/targets usage `daemons()` is ever called that often? I don't think this is an issue as NNG can handle much higher throughput than R can generate. But I wonder...

**Comment by wlandau** [comment]
`crew` does `daemons()` in a couple places: in particular, when it [starts the dispatcher and makes sure it is running](https://github.com/wlandau/crew/blob/99fb08093fd9c1c7b98b8cb34177f9e3b9f47ea8/R/crew_router.R#L198). I can try making this polling interval more gentle in the tests.

**Comment by wlandau** [comment]
And come to think of it, `targets` does its own polling. I might have to lighten that too, just for testing.

**Comment by wlandau** [comment]
Hmm...GitHub appears to be malfuncitoning today, which will delay my progress on this.

**Comment by shikokuchuo** [comment]
Hmm seems like a case of quantum mechanics - as soon as I instrument the tests to find where it's hanging https://github.com/shikokuchuo/mirai/commit/afe22c7a07e6510f4f87eb1caeabdea6e1f4441d, it no longer hangs: https://github.com/shikokuchuo/mirai/actions/runs/4926527459. I'll keep trying.

**Comment by shikokuchuo** [comment]
I think I've isolated the issue in this run: https://github.com/shikokuchuo/mirai/actions/runs/4926942122/jobs/8803210469. It triggers when I remove the `cat()` line between the following 2 commands. So it might be that there needs to be an infinitesimal gap of time after a server connects to launching a task. I'm afraid I can't sync the daemon launch as it connects to dispatcher rather than the client.

```r
launch_server(url = url)
task <- mirai(
    .expr = targets:::target_run(target, globalenv(), "_targets"),
    .args = list(target = target),
    .timeout = 60000L
  )
```

**Comment by shikokuchuo** [comment]
So the above is using `launch_server()`, but the equivalent `processx` command, you might want to try adding a delay or something as a stopgap see if it solves the hanging. Then we can think if there is a more optimal solution.

**Comment by wlandau** [comment]
Thanks! I tried https://github.com/shikokuchuo/mirai/issues/53#issuecomment-1540754810, but it looks like there is still hanging: https://github.com/ropensci/targets/actions/runs/4929755261. Trying the same thing again at https://github.com/ropensci/targets/actions/runs/4929798098 but with a 100ms delay after detecting a connection.

**Comment by shikokuchuo** [comment]
Yes, it seems to be that poll loop which is problematic: https://github.com/shikokuchuo/mirai/actions/runs/4929764794/jobs/8809815414#step:7:673 You can see that it always stops at 'daemons set', it never reaches the next marker which is 'got status', so it hangs during that loop.

This is after I decreased the polling frequency to 0.5s. So it can't be the case that messages are being dropped or anything like that. The receive also has a timeout built in. It's not obvious so I'll have to mull over this one.

But if there is a way to work around having to poll in the first place, I'd definitely go for that.

**Comment by wlandau** [comment]
Sounds like a tough problem, but it's really encouragning how closely you have nailed down the problem.

An update: unsurprisingly, my version of https://github.com/shikokuchuo/mirai/issues/53#issuecomment-1540792207 with the 100ms delay still showed hanging tests: https://github.com/ropensci/targets/actions/runs/4929798098.

**Comment by shikokuchuo** [comment]
I believe I have it! As I mentioned elsewhere, in `mirai` 0.8.4, the status matrix is constructed by the client, not sent as an object by dispatcher. This means that the server URLs are actually cached by `mirai` whenever the bus connection is established / `saisei()` is called.

Hence to find out the URL, you don't need to query `daemons()` at all - the URLs are stored as a character vector under the relevant `.compute` environment at `$urls` e.g. here: https://github.com/shikokuchuo/mirai/blob/dev/tests/tests.R#L11

There is no public interface at present, but I am sure you can implement a workaround for now. I can make one available in the next release (am afraid the current update is already in a CRAN queue).

It seems to work in this test run with 0.1s between polls: https://github.com/shikokuchuo/mirai/actions/runs/4930262246

**Comment by wlandau** [comment]
At a high level, I can see how this fixes the example from https://github.com/shikokuchuo/mirai/issues/53#issuecomment-1539035394. And it's extremely helpful how you have isolated the problem. However, `crew` and its users frequently poll `daemons()` for other reasons besides discovering the URLs.

1. When a `crew` controller starts, it [polls `daemons()` until it receives confirmation that the dispatcher is running](https://github.com/wlandau/crew/blob/d92d2c4e23cd737429aa718393875033d77da5c2/R/crew_router.R#L231) (or it times out). This still seems like a necessary step before launching servers because `crew` needs `asyncdial = FALSE`. (I forget where we talked about `asyncdial = FALSE`, but I think `crew` needs it in order to avoid the case of orphaned servers that try to connect after the startup window expired and the socket already rotated with `saisei()`.)
2. Every call to `controller$pop()` [auto-scales the workers](https://github.com/wlandau/crew/blob/d92d2c4e23cd737429aa718393875033d77da5c2/R/crew_controller.R#L368-L369), which is important for handling transient workers with a long backlog of tasks. Every auto-scaling operation [needs to poll `daemons()` again](https://github.com/wlandau/crew/blob/d92d2c4e23cd737429aa718393875033d77da5c2/R/crew_controller.R#L228) in order to [check the `online` and `instance`](https://github.com/wlandau/crew/blob/d92d2c4e23cd737429aa718393875033d77da5c2/R/crew_controller.R#L567-L576) fields to see which workers are connected, discovered, and lost. In `targets` and Shiny, these calls to `controller$pop()` need to happen several times a second in order to be efficient.

**Comment by shikokuchuo** [comment]
> At a high level, I can see how this fixes the example from [#53 (comment)](https://github.com/shikokuchuo/mirai/issues/53#issuecomment-1539035394). And it's extremely helpful that you have isolated the problem. However, `crew` and its users frequently poll `daemons()` for other reasons besides discovering the URLs.

I realise I've just given you the answer without the explanation! To be clear, after the further investigation yesterday, I've found no issue whatsoever with polling. The precise issue was calling for a `daemons()` status *immediately* after setting daemons, which fails in possibly 1 in 20 cases on Github. I have yet to reproduce this locally.

>     1. When a `crew` controller starts, it [polls `daemons()` until it receives confirmation that the dispatcher is running](https://github.com/wlandau/crew/blob/d92d2c4e23cd737429aa718393875033d77da5c2/R/crew_router.R#L231) (or it times out). This still seems like a necessary step before launching servers because `crew` needs `asyncdial = FALSE`. (I forget where we talked about `asyncdial = FALSE`, but I think `crew` needs it in order to avoid the case of orphaned servers that try to connect after the startup window expired and the socket already rotated with `saisei()`.)

This is absolutely not necessary any more as the socket connection is synced since mirai 0.8.4. If setting daemons returns you are good to go - the call *will* error if the client cannot sync with dispatcher and times out. Just retrieve the URLs directly to launch the servers - again these will be available if the daemons call returns (polling doesn't help). FYI the dispatcher pid is also available at `$pid` in the `.compute` environment.

>     2. Every call to `controller$pop()` [auto-scales the workers](https://github.com/wlandau/crew/blob/d92d2c4e23cd737429aa718393875033d77da5c2/R/crew_controller.R#L368-L369), which is important for handling transient workers with a long backlog of tasks. Every auto-scaling operation [needs to poll `daemons()` again](https://github.com/wlandau/crew/blob/d92d2c4e23cd737429aa718393875033d77da5c2/R/crew_controller.R#L228) in order to [check the `online` and `instance`](https://github.com/wlandau/crew/blob/d92d2c4e23cd737429aa718393875033d77da5c2/R/crew_controller.R#L567-L576) fields to see which workers are connected, discovered, and lost. In `targets` and Shiny, these calls to `controller$pop()` need to happen several times a second in order to be efficient.

I don't see any issue with this. Hope everything is clear now. Good luck with the tests!

**Comment by wlandau** [comment]
That's really useful info, and it allowed me to simplify `crew` quite a lot: https://github.com/wlandau/crew/commit/ff833e7dfff89797ae5c4bc8b04d4ad30a2e121a. But unfortunately, I still see hanging tasks on my end: https://github.com/ropensci/targets/actions/runs/4936193312/jobs/8823439823. Based on previous logs, this is happening when checks on `daemons()` are okay, but a `mirai` tasks stays in an unresolved state indefinitely. It's really hard to reproduce without `targets`.

**Comment by wlandau** [comment]
I wonder, could it have something to do with repeated calls to `daemons()` combined with repeated calls to `nanonext::.unresolved()`?

**Comment by shikokuchuo** [comment]
That's really good that it's allowed you to simplify things. I don't see how repeated calls to the above functions can cause problems.

Would you mind testing the latest build of mirai v. 0.8.4.9004 [85953f8](https://github.com/shikokuchuo/mirai/commit/85953f80e2d0727fcccbfe847679f8dffec9906b)? I got CRAN feedback and I'm doing final tests on it. Notable change is that the default `asyncdial` is now FALSE across the package for additional safety. Also caught one bug in `saisei()`.

**Comment by shikokuchuo** [comment]
> I wonder, could it have something to do with repeated calls to `daemons()` combined with repeated calls to `nanonext::.unresolved()`?

This is a tricky issue. I just ran the tests from yesterday again just to confirm - and they do appear to be fixed - just through not polling `daemons()` right at the start. But perhaps it is still something to do with polling.

Did you have any specific concern with `nanonext::.unresolved()`? I don't believe that function has the capacity to hang as it is essentially just reading an `int` in a C struct on the local process.

**Comment by wlandau** [comment]
With `mirai` 0.8.4.9004, the hanging is rare, but it still happens: https://github.com/ropensci/targets/actions/runs/4936588271/jobs/8824297563. From previous tests, I believe this is still a case where the dispatcher is running, `daemons()` polls just fine, and the server is running fine, but the task is still stuck at unresolved. 

I have not been able to isolate this in a small reproducible example without `targets`, even after weeks of trying, so I wonder if it would be possible to run the same tests on a dev fork of `mirai` which prints a verbose log (or even a trace).

**Comment by shikokuchuo** [comment]
> With `mirai` 0.8.4.9004, the hanging is rare, but it still happens: https://github.com/ropensci/targets/actions/runs/4936588271/jobs/8824297563. From previous tests, I believe this is still a case where the dispatcher is running, `daemons()` polls just fine, and the server is running fine, but the task is still stuck at unresolved.
> 
Thanks! At least it is no worse than before.

> I have not been able to isolate this in a small reproducible example without `targets`, even after weeks of trying, so I wonder if it would be possible to run the same tests on a dev fork of `mirai` which prints a verbose log (or even a trace).

Let me know what you want to try. I was going to suggest if it was at all possible to instrument the tests a bit (so we can try to isolate where exactly it is hanging).

I just had a thought - as the tests from yesterday were all just all repeatedly doing one run, which now succeeds. In the targets tests that fail, is `saisei()` being called? I wonder if it is to do with switching the listeners between tasks. Do you have any tests in which `saisei()` isn't called for comparison?

**Comment by wlandau** [comment]
> Let me know what you want to try. I was going to suggest if it was at all possible to instrument the tests a bit (so we can try to isolate where exactly it is hanging).

If you have any suggestions for how to isolate the tests, I am eager to try. As soon as I try to peel back the layers, either the test passes or the error is different.

> I just had a thought - as the tests from yesterday were all just all repeatedly doing one run, which now succeeds. In the targets tests that fail, is saisei() being called?

I checked locally, and those `targets` tests actually do not call `saisei()` at all.

**Comment by shikokuchuo** [comment]
That's good to know re. `saisei()`, that certainly narrows things down.

I am a fan of lots of print statements, but I have first hand experience of the disappearing failures from yesterday.

Let me have a think. I'm also going to attempt another CRAN release in the meantime (wish me luck!).

**Comment by HenrikBengtsson** [comment]
Drive-by comment: It sounds like you cannot reproduce the GitHub Actions
issues locally. GitHub Actions runs with two CPU cores. Although less
complicated than this, I had corner cases way back that only appeared when
running on hosts with a single or two cores. If this is the case here,
Linux containers provide ways to limit the CPU resources. Alt, Posit Cloud
Free runs on a single core, so maybe worth a try to reproduce there. Again,
just a thought.

**Comment by shikokuchuo** [comment]
> Drive-by comment: It sounds like you cannot reproduce the GitHub Actions issues locally. GitHub Actions runs with two CPU cores. Although less complicated than this, I had corner cases way back that only appeared when running on hosts with a single or two cores. If this is the case here, Linux containers provide ways to limit the CPU resources. Alt, Posit Cloud Free runs on a single core, so maybe worth a try to reproduce there. Again, just a thought.


Thanks @HenrikBengtsson ! Didn't realise you were still receiving these - apologies for the volume!! I will sign up for Posit Cloud - seems worth a try.

**Comment by shikokuchuo** [comment]
> I checked locally, and those `targets` tests actually do not call `saisei()` at all.

Another thought. The targets tests do they make use of timeouts/auto-scaling?

Just looking through the code again, one possibility is that the dispatcher has sent the task but somehow the server has exited and the disconnection has not been registered. Hence it is just waiting to receive when there is no actual server. I don't know how this can be yet. But to rule out this possibility, is it possible to run the tests on a vanilla non-scaling, no timeout daemons setting?

**Comment by wlandau** [comment]
Thanks, @HenrikBengtsson. I did try a GitHub Codespace based on https://github.com/ropensci/targets/blob/debug-targets/Dockerfile, which has similar resources, but I could not produce the exact type of hanging I see on GitHub Actions. Posit Cloud is a great idea.

@shikokuchuo, all the `targets` tests do make use of auto-scaling, but the only timeouts are the `R.utils::withTimeout()` wrapper around everything to anticipate the hanging. From what I remember from the previous test output, the server process is actually still running, which I confirmed with both `daemons()$daemons` and printing the `processx` handle. I just reinserted some logging to confirm.

**Comment by wlandau** [comment]
> From what I remember from the previous test output, the server process is actually still running, which I confirmed with both daemons()$daemons and printing the processx handle

Indeed, from https://github.com/ropensci/targets/actions/runs/4941225899/jobs/8833634834#step:8:341, it looks like that server process is still actually running. From https://github.com/ropensci/targets/actions/runs/4941225899/jobs/8833634834#step:8:332, the server is online and has received a task but has not completed it.

**Comment by wlandau** [comment]
I also ran a round of tests that disabled auto-scaling: I manually launched all the workers beforehand up front, waited 3 seconds, and then allowed the pipeline of tasks to start. Looks like I see the same hanging where the dispatcher and server look fine by all accounts (NNG + `processx` handles) but the task stays unresolved indefinitely: https://github.com/ropensci/targets/actions/runs/4941363308/jobs/8833895886.

**Comment by shikokuchuo** [comment]
> > From what I remember from the previous test output, the server process is actually still running, which I confirmed with both daemons()$daemons and printing the processx handle
> 
> 
> 
> Indeed, from https://github.com/ropensci/targets/actions/runs/4941225899/jobs/8833634834#step:8:341, it looks like the R process of the server is still actually running, as seen from the output of the `processx` handle. From https://github.com/ropensci/targets/actions/runs/4941225899/jobs/8833634834#step:8:332, the server is online and has received a task but has not completed it.

What would really help is to instrument the script just before and after the mirai is sent - and also from inside the mirai task have it cat to a log file before targets begins, and then one afterwards. This will confirm where it is stuck - it has not received the task, the eval is failing, or the send is failing.

**Comment by wlandau** [comment]
I doubt it has to do with #42 because the defaults in `crew_controller_local()` opt for completely persistent workers: `maxtasks = Inf`, `idletime = Inf`, `walltime = Inf`.

**Comment by shikokuchuo** [comment]
> I doubt it has to do with #42 because the defaults in `crew_controller_local()` opt for completely persistent workers: `maxtasks = Inf`, `idletime = Inf`, `walltime = Inf`.

One thing that came to me was: in the tests do you actually retrieve the results by accessing $data or using unresolved (rather than .unresolved)? If you don't the individual contexts are not destroyed, in which case it is possible this becomes a resource issue. I was debugging a Windows issue on my trusty Intel Atom netbook and things were at least an order of magnitude slower. On the other hand GitHub Linux runners are supposedly dual core with 7Gb RAM, which should actually be ample power.

**Comment by wlandau** [comment]
Possibly useful: I just hit the same timeout (capped at 60s) on my local Ubuntu machine which has 4 cores and 16 GB memory.

**Comment by shikokuchuo** [comment]
> `crew` uses `.unresolved()` to check the status of the `mirai` tasks while avoiding downloading the data right away. This happens during the [`collect()`](https://github.com/wlandau/crew/blob/874d0a2cb36dea191214ffd65391d77c998506e9/R/crew_controller.R#L340) method of the controller which makes a note of all the done tasks and thus allows the right auto-scaling decisions to be made. Then in a separate step, the [`pop()`](https://github.com/wlandau/crew/blob/874d0a2cb36dea191214ffd65391d77c998506e9/R/crew_controller.R#L368) method [calls `$data` on the `mirai` object](https://github.com/wlandau/crew/blob/874d0a2cb36dea191214ffd65391d77c998506e9/R/crew_controller.R#L373) of a task previously discovered to be done. `unresolved()` is not used at all.
> 
> > in the tests do you actually retrieve the results by accessing $data or using unresolved (rather than .unresolved)? If you don't the individual contexts are not destroyed, in which case it is possible this becomes a resource issue.
> 
> Sorry, I'm not sure I understand. Does `$data` or `unresolved()` preserve contexts? And does preserving the context create a resource issue?
> 
> After retrieving the result, `pop()` [removes the last remaining reference to the task](https://github.com/wlandau/crew/blob/main/R/crew_controller.R#L401), which I would hope would allow the garbage collector to clean it up.

Thanks, it's just as I thought, which is fine. I wanted to double check my understanding. There is nothing special about `unresolved()`, it triggers the active binding the same as if it were accessed directly. This destroys the context as it is no longer of any use. I don't think this line of attack takes us anywhere.

**Comment by shikokuchuo** [comment]
@wlandau with your experiences, and also with extra testing on certain rhub configurations - I am leaning towards this being a resource issue again. NNG does create a fair amount of threads. Simulated mirai/targets heavy load tasks complete on rhub (some much quicker than others), but fail on Github. Never fail locally on my laptop. Happy to investigate more next week, but just to let you know my thoughts.

The code for sending back a completed task from the mirai is quite synchronous and robust in my opinion - it seems unlikely to be a fault there.

**Comment by wlandau** [comment]
That would make sense for GitHub Actions, as we have discussed. But as I am kicking the tires with `crew.cluster`, which allows me to run many more workers than before, I am noticing hanging tasks on a fairly light version of the types of simulation pipelines my team and I run on a regular basis. I used a powerful SGE cluster with plenty of memory, so unless there is an intrinsic maximum number of threads or there is something else I am missing, I am not sure which resources would be lacking. I opened a new issue at #58. Sorry to bother you again about this.

**Comment by shikokuchuo** [comment]
Let's port further discussion of the actual targets cases to #58. For the record I am satisfied that nanonext 0.8.3 / mirai 0.8.7/0.8.7.9001 work as intended and the just targets/mirai reprexes (after fixing a couple of bugs in them) no longer hang on Github.
